[pytest]
minversion = 6.0
addopts = -ra -q
testpaths = tests
# Retain 0 temporary directories after the test run finishes
tmp_path_retention_count = 0
# Optionally, specify a policy (always or never)
tmp_path_retention_policy = all
asyncio_mode = auto